Refactor library
OntimizeWeb/ontimize-web-ngx-report pull request #40
Opened 2022-06-07 10:31 UTC by tomfacal

Closes #28.

2022-06-08 06:18 UTC, patricia-martinez-imatia commented on projects/ontimize-web-ngx-report/src/lib/components/report/o-report-new/o-report-new.component.ts
>    ngOnInit() {
I think it is better to remove the method because it is not used

2022-06-08 14:41 UTC, daniel-grana submitted a review, later dismissed

2022-06-09 06:28 UTC, patricia-martinez-imatia requested changes

2022-06-09 11:00 UTC, patricia-martinez-imatia approved these changes

2022-06-09 11:01 UTC, merged