Modified viewer style
OntimizeWeb/ontimize-web-ngx-report pull request #42
Opened 2022-06-09 11:14 UTC by tomfacal

Closes #41.

2022-06-09 11:48 UTC, daniel-grana approved these changes

2022-06-09 12:36 UTC, patricia-martinez-imatia requested changes

2022-06-09 12:36 UTC, patricia-martinez-imatia commented on projects/ontimize-web-ngx-report/src/lib/services/o-fill-report.service.ts
>                maxHeight: '100vh',
This code is the same than line 48? I think its better to refactor

2022-06-09 12:36 UTC, patricia-martinez-imatia commented on projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.ts
> +  setFullscreenDialog(): void {
I think it is better to move this method to a utils file because its used in other component too

2022-06-09 14:34 UTC, daniel-grana approved these changes

2022-06-10 06:35 UTC, patricia-martinez-imatia approved these changes

2022-06-10 06:35 UTC, merged